config/routes.rb
Rails.application.routes.draw do
  get 'mc_questions', to: 'mc_questions#index', as: 'mc_questions' # index
  get 'mc_questions/:id', to: 'mc_questions#show', as: 'mc_question' # show
  post 'contact', to: 'static_pages#leave_feedback', as: 'leave_feedback'
  get 'contact', to: 'static_pages#contact', as: 'contact'
  get 'welcome', to: 'static_pages#welcome', as: 'welcome'
  get 'about', to: 'static_pages#about', as: 'about'
  root to: redirect('/welcome', status: 302)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mc_question.rb
class McQuestion < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mc_questions_controller.rb
class McQuestionsController < ApplicationController
  def index
    questions = McQuestion.all
    respond_to do |format|
      format.html { render :index, locals: { questions: questions } }
    end
  end

  def show
    question = McQuestion.find(params[:id])
    respond_to do |format|
      format.html { render :show, locals: { question: question } }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def leave_feedback
    required = [:name, :email, :reply, :feedback_type, :message]
    form_complete = true
    required.each do |f|
      if params.has_key? f and not params[f].blank?
        # that's good news. do nothing
      else
        form_complete = false
      end
    end
    if form_complete
      form_status_msg = 'Thank you for your feedback!'
    else
      form_status_msg = 'Please fill in all the remaining form fields and resubmit.'
    end
    respond_to do |format|
      format.html { render :contact, locals: { status_msg: form_status_msg, feedback: params } }
    end
  end
  
  def contact
    respond_to do |format|
      format.html { render :contact, locals: { feedback: {} } }
    end
  end

  def welcome
    features = [
      'Choose from premade quizzes on a variety of topics',
      'Make your own quizzes to customize your learning',
      'Compare your scores with other users'
    ]
 
    respond_to do |format|
      format.html { render :welcome, locals: { features: features } }
    end
  end

  def about
    respond_to do |format|
      format.html { render :about }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mc_questions_helper.rb
module McQuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mc_questions/index.html.erb
<h1>Multiple Choice Questions</h1>

<% questions.each do |question| %>
    <div id="<%= dom_id(question) %>">
        <p><%= question.question %></p>

        <%
        choices = [question.answer, question.distractor_1, question.distractor_2]
        choices.each do |c|
        %>
        <div>
            <%= radio_button_tag "guess_#{question.id}", c, checked = c == question.answer, disabled: true %>
            <%= label_tag "guess_#{question.id}_#{c}", c %>
        </div>

        <% end %>
    </div>
<% end %>

app/views/mc_questions/show.html.erb
<p><%= question.question %></p>

<%
choices = [question.answer, question.distractor_1, question.distractor_2]
choices.each do |c|
%>
  <div class="custom-control custom-radio">
    <%= radio_button_tag "guess", c, checked = c == question.answer, disabled: true %>
    <%= label_tag "guess_#{c}", c %>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>

<h2>The Authors</h2>

<p>This site was created by Scott Fleming and Katie Bridson.</p>

<p><%= link_to 'Welcome', welcome_path %></p>

app/views/static_pages/contact.html.erb
<h1>Contact Us</h1>

<p>We welcome your feedback. Please submit the form below to let us know what you think or alert us to any problems you are having with QuizMe.</p>

<h2>Feedback</h2>

<% if local_assigns.has_key? :status_msg %>
   <p><%= status_msg %></p>
<% end %>

<%= form_with url: leave_feedback_path, local: true, method: :post do %>
    <div>
        <%= label_tag "name" %>
        <%= text_field_tag "name", feedback.fetch(:name, nil) %>
    </div>
    <div>
        <%= label_tag "email" %>
        <%= email_field_tag "email", feedback.fetch(:email, nil) %>
    </div>
    <div>
        <span>Can we contact you by email?</span>
        <div>
            <%= radio_button_tag "reply", true, feedback.fetch(:reply, nil) == true.to_s %>
            <%= label_tag "reply_yes", 'Yes' %>
        </div>
        <div>
            <%= radio_button_tag "reply", false, feedback.fetch(:reply, nil) == false.to_s %>
            <%= label_tag "reply_no", 'No' %>
        </div>
    </div>
    <div>
        <%= label_tag "feedback_type" %>
        <%= select_tag "feedback_type", options_for_select([ "Review", "Bug Report" ], feedback.fetch(:feedback_type, "")), prompt: 'Choose one...' %>
    </div>
    <div>
        <%= label_tag "message" %><br>
        <%= text_area_tag "message", feedback.fetch(:message, nil), size: "27x7" %>
    </div>
    <%= submit_tag "Send Feedback" %>
<% end %>

<p><%= link_to 'Welcome', welcome_path %></p>

app/views/static_pages/welcome.html.erb
<h1>Welcome to QuizMe!</h1>

<%= image_tag "quiz-bubble.png", height: 300 %>

<p>
   QuizMe is a free <%= link_to "Quizlet", "https://quizlet.com", target: "_blank" %> style quizzing application that helps you learn by taking quizzes and trying to improve your scores.
 </p>
 
<h2>Features</h2>

 <p>
   QuizMe allows users to:
 </p>

 <ul>
  <% features.each do |f| %>
    <li><%= f %></li>
  <% end %>
 </ul>

 <p>
   QuizMe also supports a variety of question styles like multiple choice and fill in the blank.
 </p>

 <p><%= link_to "About", about_path %></p>
 <p><%= link_to "Contact", contact_path %></p>
 